title: Edmund Haacke
markdown: kramdown

# for atom feed
author:
  name: Edmund Haacke
  email: hello@edmundhaacke.com

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
